### ISSUE TITLE
replace origin with rpId in rpId hash check

### ISSUE THREAD

**Issue by vigan-abd** [FIDO-Tools/fido2-library#13]
Hi @JamesCullum could you do the [same](https://github.com/webauthn-open-source/fido2-lib/pull/52) here? This feature seems really helpful for verification on subdomains and makes the lib more compatible with libs in other languages like ruby

**Comment by JamesCullum** [comment]
Hey vigan, lets try to prevent tracking the same issue multiple times. The PR has been marked as draft because the creator wanted to do some larger changes that weren't done.

If you are interested in this functionality and can work on the shortcomings, feel free to do so and create a new PR.

**Comment by vigan-abd** [comment]
thanks for quick response, alright I'll open a PR here with additional support and keeping backward compatibility
