### ISSUE TITLE
Integrity Check Error

### ISSUE THREAD

**Issue by luckycreationsindia** [FIDO-Tools/fido2-library#17]
Hi,

I'm getting following error while installing fido2-library

` tarball data for fido2-library@https://registry.npmjs.org/fido2-library/-/fido2-library-2.6.0.tgz (sha512-rMySX7kJkQaFPNQxkwUEN3RdGFiUqRw8WIZPgggdyRdL1IH7mKjWgOcZwGWoUQBUAKgE6YYbEETGE0N1S7I6VA==) seems to be corrupted. Trying again.

   tarball data for fido2-library@https://registry.npmjs.org/fido2-library/-/fido2-library-2.6.0.tgz (sha512-rMySX7kJkQaFPNQxkwUEN3RdGFiUqRw8WIZPgggdyRdL1IH7mKjWgOcZwGWoUQBUAKgE6YYbEETGE0N1S7I6VA==) seems to be corrupted. Trying again.

   EINTEGRITY
  sha512-rMySX7kJkQaFPNQxkwUEN3RdGFiUqRw8WIZPgggdyRdL1IH7mKjWgOcZwGWoUQBUAKgE6YYbEETGE0N1S7I6VA== integrity checksum failed when using sha512: wanted sha512-rMySX7kJkQaFPNQxkwUEN3RdGFiUqRw8WIZPgggdyRdL1IH7mKjWgOcZwGWoUQBUAKgE6YYbEETGE0N1S7I6VA== but got sha512-VLRAcYdF+nZcgiDBM8AjKRkDyQIe5sNMySr4YaxR210yxsjvqGyOAbM5GW0ZzqOPIRhqQOuAYWxrtFoifphIng==. (93368 bytes)`

**Comment by JamesCullum** [comment]
Hey there, thanks for the report. Sadly this indicates some issue on your workstation that we cannot debug - it could be a broken installation, a proxy issue etc. You can try out different internet tricks to find the reason: https://stackoverflow.com/questions/58989195/npm-package-seems-to-be-corrupted

**Comment by luckycreationsindia** [comment]
Hi,

There was a problem with integrity check the day I posted this issue. Just checked, it's working fine.

Don't know what exactly caused this issue. Maybe issue was from npm side.

**Comment by luckycreationsindia** [comment]
There's still issue with integrity check. I checked on multiple devices. Currently I'm using github url reference for my code as a work around.

Edit:

I tried multiple workarounds but none of them worked.

I cleared cache.
I tried using mobile data.
Reinstalled both node and npm.
Reinstalled node-gyp.
Delete package-lock.json
Delete node_modules folder.
