### ISSUE TITLE
Missing allowCredentials in PublicKeyCredentialRequestOptions

### ISSUE THREAD

**Issue by efabris** [FIDO-Tools/fido2-library#20]
Hello @JamesCullum,

as specified by [WebAuthn specification](https://w3c.github.io/webauthn/#dictionary-assertion-options) the options for assertion generation (PublicKeyCredentialRequestOptions) also include allowCredentials field to filter what credentials could be used during login process. However I see that the library does not include this option. I'am working on adding this. When I'll finish, I'll send a pull request to you. Let me know if this is ok for you.

Thank you,

Enrico.

**Comment by JamesCullum** [comment]
Sounds good, thanks! I will close the issue here and would await your PR once ready 👍
