### ISSUE TITLE
Counter handling if counter is not supported (e. g.) safari

### ISSUE THREAD

**Issue by florianbepunkt** [FIDO-Tools/fido2-library#7]
Currently Safari supports webauthn, but the counter is always set to zero.

> The signature counter is not implemented and therefore it is always zero. Secure Enclave is used to prevent the credential private key from leaking instead of a software safeguard.

(Source: https://webkit.org/blog/11312/meet-face-id-and-touch-id-for-the-web/)

I would propose that the prevCounter verification step is skipped in validation if the prevCounter expectation and the counter value submitted in the client authData is both 0. This in line with Ackermann Yuriy's recommendation

> If counter in DB is 0, and response counter is 0, then authr does not support counter, and this step should be skipped

https://herrjemand.medium.com/verifying-fido2-responses-4691288c8770

Current behavior is that WebAuthn fails on WebKit browser due to rollback  error.

EDIT: Created a PR #8

**Comment by JamesCullum** [comment]
Thanks for the issue & PR!

**Comment by JBYoshi** [comment]
Something like this seems to be coming up again - when the counter is zero, `validateAudit()` fails [here](https://github.com/FIDO-Tools/fido2-library/blob/master/lib/validator.js#L575-L576) because `counter` is still in `authnData` but doesn't get added to the audit log.

**Comment by JamesCullum** [comment]
Can you create a PR that would solve this issue?

**Comment by JBYoshi** [comment]
See #10.
