### ISSUE TITLE
Use of vulnerable version of jwk-to-pem

### ISSUE THREAD

**Issue by Piccirello** [FIDO-Tools/fido2-library#9]
jwk-to-pem v2.0.0 makes use of a vulerable version of `elliptic`, which could allow an attacker to determine a user's private key ([advisory](https://snyk.io/vuln/SNYK-JS-ELLIPTIC-1064899)). jwk-to-pem hasn't yet been patched, but wanted to put this on your radar for when it is.

Relevant PR:
https://github.com/Brightspace/node-jwk-to-pem/pull/84

**Comment by JamesCullum** [comment]
Thanks for the hint! Once a patch is available, a PR should be created automatically. If not, let me know and we can patch asap.
